
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  devtools:
    livereload:
      enabled: true     # Spring devtools = ??????? ??? ??? ?? ??? ???? ??? ?????, ? ?????? ??? ???? ??
  servlet:
    multipart:                  #?? ???? ??? ??? ????
      max-file-size: 100MB       #???? ?? ??????? ????,
      max-request-size: 100MB    #???? request ??? ??,
  main:
    allow-circular-references: true
  thymeleaf:                    #???? ??,
    enabled: true               # ????? ??? ??? ??,
    prefix: classpath:templates/  # ????? ???? ??
    suffix: .html               # ????? ???? ??? ?? ???
    cache: false                # false? ???? ? ????? ???? ??? ???? ?? ?? ?? ????? ??? ??.??? false?? true,
    encoding: UTF-8             # ???? ??? ??
    mode: HTML                  # ????? HTML ???? HTML5,,
    check-template: true        # ??? ?? template ?? ?? ??
    check-template-location: true # template ?? ?? ?? ??
  datasource:       # HikariCP? ?????? ??, (DB??? ?? ????) ???? = DB? ??? ???? ?? ????? ?????, ?????? ???? ???? ???? ??,
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/member?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root # mysql ID
      password: 1111 # ?? MYSQL ???? ??
      connection-test-query: SELECT NOW() FROM dual
mybatis:
  configuration:
    map-underscore-to-camel-case: true #MyBatis? ???? ??????? ( ???"_" ? ??? ??? ??? ??)? ex)camel_case
    #??? ??? ????? ???? ??, ???? ?????? > ????? ??? ex)camelCase
server:
  port: 8091

